### ISSUE TITLE
I just wonder is there any one  get the dataset successfully?

### ISSUE THREAD

**Issue by kaiyanchen** [algorithmiaio/danku#1]
I got the error message: "RemoteDisconnected('Remote end closed connection without response")

**Comment by kennydaniel** [comment]
I was just able to access the input data set using the mist browser as described in the README. If there is a connection error it might be between mist browser and your ethereum client?

Can you read any of the other contract property values?

Let me know if you continue having problems. I could send you the training data here, but I expect you would hit the same problem when you try to submit something. Cheers.

**Comment by 0rb1t** [comment]
The instructions say "You also need `geth` up and running".

Does the "running" imply running a full ethereum node?

**Comment by besirkurtulmus** [comment]
@0rb1t It doesn't have to be a full running node. You can run a light node. You just need to be able to interact with the ethereum network.

**Comment by besirkurtulmus** [comment]
@kaiyanchen That looks like a Python error. Can you provide the full traceback?

**Comment by besirkurtulmus** [comment]
@kaiyanchen Running `python -W ignore competition/download_train_visualize.py` should download and print the dataset in your console/terminal.

**Comment by besirkurtulmus** [comment]
Closing this issue since there has not been a response in 7 days.
