### ISSUE TITLE
Danku is not a blockchain based solution, is it ?

### ISSUE THREAD

**Issue by umaimehm** [algorithmiaio/danku#10]
Danku blockchain logic makes no sense to me.
If i understand it correctly, its using ethereum to pay the developer for writing an A.I algorithm.
There is no involvement of blockchain in the A.I ecosystem. 

So my question is, Why is the white-paper marketting this as a blockchain solution ?
Why is there even a white-paper for this ?

**Comment by besirkurtulmus** [comment]
@umaimehm It's using Ethereum to both pay and evaluates (aka. run the neural network) on the blockchain.

The whitepaper goes into detail of how it works. For the implementation, you can check the source code in this repo.

**Comment by besirkurtulmus** [comment]
Closing this issue since there hasn't been a response in the last 7 days.
