### ISSUE TITLE
Objective

### ISSUE THREAD

**Issue by Swapnanandamuri** [algorithmiaio/danku#13]
Whats the objective of implementing neural network on block chain

**Comment by besirkurtulmus** [comment]
@Swapnanandamuri Great question.

The short answer is: It's an interesting challenge.

The long answer is the following:

* Solidity doesn't have a math library, floating point numbers, etc.
* You're only limited to 16 local variables in a single function (including function parameters).
* The gas limit is around 8 million (as of April 17th, 2018).
* Non-linear activation functions are expensive to call.
* Neural networks are very computationally expensive.
* Storing things on the ethereum blockchain is expensive.
* And we noticed that there wasn't a protocol for exchanging ML models, even though there was some hype around ML + blockchain.

We're engineers, and we love solving problems. Running a neural network on the ethereum blockchain was a problem worth tackling.

**Comment by besirkurtulmus** [comment]
Closing the issue since there hasn't been any activity in the last 7 days.
