### ISSUE TITLE
Failed with Python3.6, but worked with Python3.5

### ISSUE THREAD

**Issue by DeepBrainC** [algorithmiaio/danku#16]
"Danku/venv/include/secp256k1" failed with error code 1 in /tmp/pip-install-hskeszz1/secp256k1" was reported when I compiled it with python3.6. After I change it to Python3.5, this error was not reported any more. What was the problem?

**Comment by DeepBrainC** [comment]
I think the problem comes from the mismatch of  the version of virtualenv

**Comment by besirkurtulmus** [comment]
That's probably the reason.

You said that it worked with a different version on virtualenv.

Which versions did you compare?

**Comment by DeepBrainC** [comment]
15.1.0 and 16.0.0
But whatever version I use, Python3.5 works well

**Comment by besirkurtulmus** [comment]
Good to know.

Closing this issue since now there's a solution.

Thanks for posting this!
