### ISSUE TITLE
TypeError: 'ellipsis' object is not iterable"

### ISSUE THREAD

**Issue by DeepBrainC** [algorithmiaio/danku#17]
"File "/usr/lib/typing.py", in _get_type_vars for t in types: TypeError: 'ellipsis' object is not iterable" was reported when I tried "populus compile." How can I solve this problem?

**Comment by DeepBrainC** [comment]
I am not sure if this problem is caused by the conflict of the name of packages, but I somehow skipped the problem by building a new environment.

**Comment by besirkurtulmus** [comment]
Closing issue since it was fixed w/ new environment.

It would be great if you can describe the difference between the environments for reference purposes.
