### ISSUE TITLE
Is feature engineering possible?

### ISSUE THREAD

**Issue by Jeiwan** [algorithmiaio/danku#2]
It doesn't look so. Feature engineering produces new features that are later used to build models, and with the protocol explained in the paper users can submit only models with the same set of features as were submitted by the buyer.

P.S. The idea is awesome!

**Comment by kennydaniel** [comment]
That's right, there's no way to modify or transform the input data set. I think with a well-designed network you could probably achieve a similar effect. Interesting idea though, thanks!
