### ISSUE TITLE
Question about the output layer

### ISSUE THREAD

**Issue by J4DE3GG** [algorithmiaio/danku#3]
For the ANN, there are two output units. Is the goal to have one unit represent the Democrat vote (0) and the other unit to represent Republican (1) or is it the sum of the two output units equal to 0 or 1 that represents the valid response of the neural network? Thanks!

**Comment by besirkurtulmus** [comment]
For output class `0` (Democrat) the network expects `[1, 0]`, and for `1` (Republican) it expects `[0, 1]`.

It doesn't compute the sum or anyhing.

The [ANN looks for these exact values](https://github.com/algorithmiaio/danku/blob/master/contracts/Danku_demo.sol#L361) while evaluating the network.

**Comment by besirkurtulmus** [comment]
Closing the issue since there's been no response.
