### ISSUE TITLE
Error running download_train_visualize.py

### ISSUE THREAD

**Issue by vanHavel** [algorithmiaio/danku#4]
After creating the virtual environment and installing the requirements, I am running
`$ python3 -W ignore competition/download_train_visualize.py`
and get the error
```Traceback (most recent call last):
  File "competition/download_train_visualize.py", line 5, in <module>
    from web3 import Web3, HTTPProvider, IPCProvider
  File "<path>/blockchain/danku/venv/lib/python3.6/site-packages/web3/__init__.py", line 5, in <module>
    from web3.main import Web3
  File "<path>/blockchain/danku/venv/lib/python3.6/site-packages/web3/main.py", line 6, in <module>
    from eth_utils import (
ImportError: cannot import name 'force_text'
```

there also seems to be a problem with 'coerce_args_to_text' from eth_utils. This is strange because I assume the right version of these libraries should get installed in the venv... Could it have something to do with using Python3 for this? The system is OS X.

**Comment by vanHavel** [comment]
You are using deprecated functions of eth_utils. Downgrading eth_utils to 0.8.1 resolves this error.

**Comment by hammeWang** [comment]
try
`pip install web3`

**Comment by besirkurtulmus** [comment]
@vanHavel Looks like it's [an issue](https://github.com/ethereum/eth-utils/issues/81) with populus.

Upgrading web3 should fix it: `pip install --upgrade web3`
