### ISSUE TITLE
Cannot EXECUTE in MIST

### ISSUE THREAD

**Issue by smalldog3** [algorithmiaio/danku#7]
In the MIST, submission is not executable.  

![image](https://user-images.githubusercontent.com/31265790/37860455-aa767d52-2efb-11e8-8cac-11a7b25f2a3d.png)

**Comment by besirkurtulmus** [comment]
Can you please provide the whole screenshot of your submission blacked out?

Also, do you have enough gas in your wallet to send the transaction?

**Comment by smalldog3** [comment]
Do you mean I need to buy ether before submission? ( I got "Territory not Supported" error when buy ETH)
Below is the whole screenshot:
![image](https://user-images.githubusercontent.com/31265790/37867670-2ab00594-2f72-11e8-9a75-8a97e708a281.png)

**Comment by besirkurtulmus** [comment]
@smalldog3 Yes, you need to have some ether in your account to be able to submit your model.

**Comment by smalldog3** [comment]
@besirkurtulmus Thank you!

**Comment by besirkurtulmus** [comment]
@smalldog3 You're welcome!
